name: sophia_hotel

services:
  auth-service:
    container_name: auth-service
    build:
      context: ../
      target: runtime
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
      - DATABASE_URL=jdbc:postgresql://dpg-d0fhdnc9c44c73bca3mg-a.singapore-postgres.render.com/userdb_q40t
      - DATABASE_USERNAME=userdb_q40t_user
      - DATABASE_PASSWORD=41rtQTmfhOhlMEh1Zy8rO6Z0gIvpcsXj
    networks:
      - sophia_hotel

volumes:
  postgres:

networks:
  sophia_hotel:
    driver: bridge