name: sophia_hotel

services:
  auth-service:
    container_name: auth-service
    build:
      context: ../
      target: runtime
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=https://sophia-hotel-discovery-service-xq0g.onrender.com/eureka/
      - DATABASE_URL=jdbc:postgresql://user-postgres:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - postgres
    networks:
      - sophia_hotel

  postgres:
    container_name: user-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - sophia_hotel

volumes:
  postgres:

networks:
  sophia_hotel:
    driver: bridge