name: sophia_hotel

services:
  auth-service:
    container_name: auth-service
    build:
      context: ../
      target: runtime
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
      - DATABASE_URL=jdbc:postgresql://dpg-cvr5eu3e5dus7386g53g-a.singapore-postgres.render.com/user_postgres
      - DATABASE_USERNAME=user_postgres_user
      - DATABASE_PASSWORD=X7GZQQZNUwirG8JfyLoWxyq6HJC89aIa
    networks:
      - sophia_hotel

volumes:
  postgres:

networks:
  sophia_hotel:
    driver: bridge